name: scraper-san-juan-gobierno

on:
  schedule:
    - cron: '0 12 * * *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run sj-gobierno.py to get the latest data
      
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git commit -m "upate jjb and action POST yamlusps" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
    
